FROM registry.access.redhat.com/ubi9
ARG USER_HOME_DIR="/home/user"

ENV HOME=${USER_HOME_DIR} \
    BUILDAH_ISOLATION=chroot \
    PIP_OPTS=--no-build-isolation

COPY --chown=0:0 entrypoint.sh /

RUN dnf --disableplugin=subscription-manager --nodocs --allowerasing install -y openssl git tar shadow-utils bash zsh podman buildah skopeo python3.11-devel python3.11 python3.11-pip aardvark-dns ; \
    dnf update -y ; \
    dnf clean all ; \
    mkdir -p ${WORK_DIR} ; \
    chgrp -R 0 /home ; \
    ln -s /projects/bin/oc /usr/local/bin/oc ; \
    ln -s /projects/bin/kubectl /usr/local/bin/kubectl

ADD --chown=0:0 requirements.txt requirements.txt

RUN alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1 && \
    alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 50 && \
    alternatives --install /usr/bin/python python /usr/bin/python3.9 1 && \
    alternatives --install /usr/bin/python python /usr/bin/python3.11 50 && \
    alternatives --install /usr/bin/pip3 pip3 /usr/bin/pip3.11 50 && \
    alternatives --install /usr/bin/pip pip /usr/bin/pip3.11 50

RUN pip install --no-cache-dir -r requirements.txt

#
# Setup for root-less podman
#
RUN mkdir -p ${USER_HOME_DIR} ; \
    mkdir -p ${USER_HOME_DIR}/.config/containers ; \
    (echo '[storage]';echo 'driver = "overlay"';echo 'graphroot = "/tmp/graphroot"';echo '[storage.options.overlay]';echo 'mount_program = "/usr/bin/fuse-overlayfs"') > ${USER_HOME_DIR}/.config/containers/storage.conf ; \
    chown -R 1000:1000 ${USER_HOME_DIR} ; \
    echo "user:x:1000:0:devspaces user:${USER_HOME_DIR}:/bin/bash" >> /etc/passwd ; \
    echo "user:x:1000:" >> /etc/group ; \
    echo "user:1001:64535" >> /etc/subuid ; \
    echo "user:1001:64535" >> /etc/subgid ; \
    setcap cap_setuid+ep /usr/bin/newuidmap ; \
    setcap cap_setgid+ep /usr/bin/newgidmap ; \
    chmod +x /entrypoint.sh

USER 1000
ENTRYPOINT ["/usr/libexec/podman/catatonit","--","/entrypoint.sh"]
CMD [ "tail", "-f", "/dev/null" ]
